# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bmiGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from math import trunc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(738, 300)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 240, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 100, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 111, 16))
        self.label_3.setObjectName("label_3")
        self.pounds = QtWidgets.QLineEdit(Dialog)
        self.pounds.setGeometry(QtCore.QRect(160, 100, 61, 22))
        self.pounds.setObjectName("pounds")
        self.feet = QtWidgets.QLineEdit(Dialog)
        self.feet.setGeometry(QtCore.QRect(160, 170, 61, 22))
        self.feet.setObjectName("feet")
        self.inches = QtWidgets.QLineEdit(Dialog)
        self.inches.setGeometry(QtCore.QRect(270, 170, 61, 22))
        self.inches.setObjectName("inches")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(230, 100, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(230, 170, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(340, 170, 41, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(540, 70, 41, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(490, 140, 55, 16))
        self.label_8.setMaximumSize(QtCore.QSize(55, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(450, 210, 101, 16))
        self.label_9.setObjectName("label_9")
        self.bmi = QtWidgets.QLineEdit(Dialog)
        self.bmi.setGeometry(QtCore.QRect(580, 140, 113, 22))
        self.bmi.setObjectName("bmi")
        self.range = QtWidgets.QLineEdit(Dialog)
        self.range.setGeometry(QtCore.QRect(580, 210, 113, 22))
        self.range.setObjectName("range")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(403, 0, 20, 301))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton.clicked.connect(self.buttonClick)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Calculate"))
        self.label.setText(_translate("Dialog", "Enter your weight."))
        self.label_2.setText(_translate("Dialog", "Enter your height."))
        self.label_3.setText(_translate("Dialog", "Calculate your BMI!"))
        self.label_4.setText(_translate("Dialog", "pounds"))
        self.label_5.setText(_translate("Dialog", "feet"))
        self.label_6.setText(_translate("Dialog", "inches"))
        self.label_7.setText(_translate("Dialog", "Results"))
        self.label_8.setText(_translate("Dialog", "Your BMI:"))
        self.label_9.setText(_translate("Dialog", "Your BMI Range:"))

    def buttonClick(self):
        pounds = int(self.pounds.text())
        feet = int(self.feet.text())
        inches = int(self.inches.text())
        height = (feet * 12) + inches
        weight = pounds * .45
        height = (height * .025) ** 2
        bmi = weight / height
        bmi = trunc(bmi * 100) / 100
        self.bmi.setText(str(bmi))
        if bmi < 18.6: self.range.setText("Underweight")
        elif bmi < 25: self.range.setText("Normal Weight")
        elif bmi < 30: self.range.setText("Overweight")
        else: self.range.setText("Obese")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
